### create a person
POST http://localhost:4004/carbon/Person
Content-Type: application/json

{
    "firstName":"Robert",
    "lastName":"Patru",
    "email":"rpatru@gmail.com"
}


### create a person
POST http://localhost:4004/carbon/PersonCredential
Content-Type: application/json

{
    "person_email":"rpatru@gmail.com",
    "password":"Hackaton@2023"
}

### create a person
GET http://localhost:4004/carbon/loginCheck(email='ITravelClean@demo.com',password='Hackaton@2023')
Content-Type: application/json

###
POST http://localhost:4004/carbon/loadRoad
Content-Type: application/json

{
    "email":"mipop@gmail.com",
    "request":[
        {
            "startPoint":"Bruxelles123",
            "endPoint":"Bruxelles",
            "transportType":"Train",
            "UoM":"km",
            "distance":"100"
        }
    ]
}

###
POST http://localhost:4004/carbon/AddRoomParticipant
Content-Type: application/json

{
    "email":"mipop@gmail.com",
    "roomID":"5e3f6551-5656-4e6e-8ae1-a24d85e82862"
}

### get nearest airport
GET http://localhost:4004/carbon/getNearestAirport(latitude='49.9397907',longitude='22.2611915')


###

GET http://localhost:4004/carbon/getMyRooms(email='ITravelClean@demo.com')
Content-Type: application/json


###

GET http://localhost:4004/carbon/GetDepartmentParticipantsTop15(roomID='051a50cb-3378-434d-bead-87c283f55b2c')
Content-Type: application/json